name: Check
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    env:
      BITVAVO_API_KEY: ${{ secrets.BITVAVO_API_KEY }}
      BITVAVO_API_SECRET: ${{ secrets.BITVAVO_API_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --all-features

  format:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add rustfmt
      - run: cargo fmt --check

  lint:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add clippy
      - run: cargo clippy --all-features -- -D warnings
